version: '3'
services:

  php-fpm:
    build: ./php-fpm/.
    volumes: ['code-data:/var/www/html', './php-fpm/logs:/var/log/']
    links: 
     - mysql
     - redis
    depends_on:
     - mysql
     - redis

  nginx:
    build: ./nginx/.
    volumes: ['code-data:/var/www/html', './nginx/logs:/var/log/nginx']
    links:
      - php-fpm
    depends_on:
      - php-fpm

  mysql:
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=magento
     - MYSQL_USER=magento
     - MYSQL_PASSWORD=magento
    build: ./mysql/.
    ports:
     - "3306:3306"
    volumes: ['db-data:/var/lib/mysql', './mysql/logs:/var/log']

  redis:
    build: ./redis/.
    volumes: ['./redis/logs:/var/log']

  varnish:
    build: ./varnish/.
    ports:
      - "80:80"
    volumes: ['./varnish/logs:/var/log']
    links:
     - nginx
    depends_on:
     - nginx

volumes:
  db-data: {}
  code-data: {}
      
