version: '3'
services:

  php-fpm:
    build: ./php-fpm/.
    volumes: ['./code:/var/www/html', './php-fpm/logs:/var/log/']
    links: 
     - mysql
    depends_on:
     - mysql

  nginx:
    build: ./nginx/.
    ports:
      - "80:80"
    volumes: ['./code:/var/www/html', './nginx/logs:/var/log/nginx']
    links:
      - php-fpm
    depends_on:
      - php-fpm

  mysql:
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=magento
     - MYSQL_USER=magento
     - MYSQL_PASSWORD=magento
    build: ./mysql/.
    ports:
     - "3306:3306"
    volumes: ['db-data:/var/lib/mysql', './mysql/logs:/var/log']

volumes:
  db-data: {}
      
